#!/bin/bash
# Copy README.md files from folders listed in ./modules file

usage="Execute to copy README.md files to this folder"
username=''
while getopts ':h' option; do
  case "$option" in
    h) echo "$usage"
    exit
    ;;
  esac
done

echo "Syncing README.md files"
while read line
do
  name=../$line/README.md
  echo $name
  cp $name ./$line.md
done < modules

echo "Sync completed"
